[package]
name = "xx-admin"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["study", "wx", "study_serv"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
headless_chrome = { version = "1.0.7", optional = true }
reqwest = { workspace = true, features = ["json", "multipart"] }
serde = { workspace = true }
serde_json = "1.0.108"
tokio = { version = "1.33.0", features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
toml = "0.8.6"
clap = { version = "4.4.8", features = ["derive", "error-context", "help", "std"] }
axum = "0.6.20"

wx = { path = "wx" }
study = { path = "study" }
tracing-opentelemetry = "0.22.0"
opentelemetry = { version = "0.21.0", features = ["trace"] }
opentelemetry_sdk = { version = "0.21.0", features = ["trace", "rt-tokio"] }
opentelemetry-stdout = { version = "0.2.0", features = ["trace"] }
opentelemetry-otlp = { version = "0.14.0", features = ["default"] }
opentelemetry-jaeger = "0.20.0"
form_urlencoded = "1.2.0"

[workspace.dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
chrono = "0.4.31"
serde = "1.0.190"
tracing = "0.1.40"
reqwest = "0.11.22"
