[package]
name = "study_serv"
version = "0.1.0"
edition = "2021"


[dependencies]
axum = { version = "0.6.20", optional = true }
dioxus = "0.4.0"
dioxus-fullstack = "0.4.1"
reqwest.workspace = true
serde.workspace = true
tracing-subscriber = "0.3.17"
tracing-wasm = "0.2.1"
anyhow.workspace = true
tracing.workspace = true
wx = { path = "../wx", optional = true }
study = { path = "../study", optional = true }
toml = { version = "0.8.8", optional = true }
tokio = { version = "1.34.0", features = ["full"], optional = true }
form_urlencoded = "1.2.0"

[features]
default = []
ssr = ["axum", "tokio", "dioxus-fullstack/axum", "toml", "study", "wx"]
web = ["dioxus-fullstack/web"]
